### ISSUE TITLE
Final To-Do List

### ISSUE THREAD

**Issue by kimberlykreiss** [uwescience/DSSG2023-Groundwater#9]
A running list of all the things we need to finish by this summer: 

- [ ] 00-getting-started.ipynb which has a short outline of the technical skills and technology someone needs to run our code 
- [ ] incorporating surface water file into our workflow
- [ ] documentation: README.md on our github;
- [ ] conference/abstract proposals: ADSA proposal due by Aug 15th.
- [ ] Send our results/outcome to stakeholders including EDF stakeholders, Brad Udall, etc. 
- [ ] website 
- [ ] presentation

**Comment by kimberlykreiss** [comment]
NASA answered my email and I figured out the NaN's thing. It is not a problem except over Ocean's so crossed it off this list.

**Comment by kimberlykreiss** [comment]
@mm-powell I added the task of adding in code that produces the visuals to the workflow like we talked about over chat!
